### ISSUE TITLE
[QA] show 'pending' when the folder size is not yet computed

### ISSUE THREAD

**Issue by jnweiger** [owncloud/owncloud-design-system#1402]
New folders do not show a size.

Expected behaviour:
Gui elements should not go missing unexpectedly.
New folders should show an indicator when the computation is pending. 

Suggestion: Show  a '?' where the file size should be. Give explanation about pending, file scan, etc. as a mouse over tooltip.

**Comment by individual-it** [comment]
currently #1393 changes the behaviour, so that `0 B` is shown, what is the decision? ?/0/pending ?
CC @micbar

**Comment by hodyroff** [comment]
@tbsbdr please check this out. My personal opinion is what I did in the project, "pending", ? or 0 bytes is confusing. If we can't guarantee we can show the proper bytes we just show nothing ... IMHO this is the least confusing one. Of course ideally we always know ...

**Comment by LukasHirt** [comment]
What about `calculating`? Seems the most user friendly to me :shrug:

**Comment by tbsbdr** [comment]
did i get it right, that there are situations where we permanently dont know the folder size?

**Comment by hodyroff** [comment]
That is correct. In oC10 those are mostly related to external storages. When you say calculating - the end user expects this to finish eventually and if it doesn't he will call the help desk = ticket = $100 lost at our customer ...

**Comment by micbar** [comment]
`not available`?
Showing nothing may also create some bug reports.

**Comment by LukasHirt** [comment]
> When you say calculating - the end user expects this to finish eventually

Oh, I thought it actually becomes available when scan of the external storage is done and synced with file cache 🙈

**Comment by tbsbdr** [comment]
## whats learned behavior?
Windows  File Explorer and MacOS Finder both face (kind of) the same ui-problem. and both display non-semantic information:

- Windows Explorer: "" (nothing)
- MacOS Finder: "--" (dashes)

(compare screenshots) 

## Applicable for ownCloud Web UI?
my guess why they don't show a semantic, more meaningful information like "not available" or "unknown"
--> it gives the user instantly a bad feeling because it points you you directly to a shortcoming of the system. Therefor the ui just keeps silent. But: as we usually display folder sizes, saying nothing would also be confusing.

## Suggestion:
- **use dashes** "--" in fileslist as they may occur more intended and less like a bug (eg. if you show nothing)
- **explain** in the sidebar, that this is intended behavior and provide a link to more information with a tooltip as suggested by @jnweiger 

Anything I didn't take into account?

## Windows File Explorer shows nothing
![image](https://user-images.githubusercontent.com/26610733/122541069-88113e00-d029-11eb-93b4-a27cbde63fe3.png)

## MacOS Finder shows "--" Dashes (like dropbox)
![image](https://user-images.githubusercontent.com/26610733/122541159-9fe8c200-d029-11eb-9d42-a4d58afd228e.png)

## Suggestion for ownCloud Web UI
![image](https://user-images.githubusercontent.com/26610733/122541848-65cbf000-d02a-11eb-8645-d252b90bb07c.png)

**Comment by individual-it** [comment]
changed #1393 to be `--`
