### ISSUE TITLE
Unexpected behavior of ocSelect width

### ISSUE THREAD

**Issue by elizavetaRa** [owncloud/owncloud-design-system#1502]
### Steps to reproduce
1. Put ocSelect Inside the Shared With Me

### Expected behaviour
The width of ocSelect fits to the longest selectable option

### Actual behaviour
The width depends on container. But for example wrapping into <div class="oc-docs-width-small"> doesn't affect the width inside Shared With Me

### Screenshots (if appropriate):
![Bildschirmfoto vom 2021-07-14 09-01-29](https://user-images.githubusercontent.com/7430156/125578021-54a18cf7-d5bf-4b97-8b72-554781fe1a06.png)

**Comment by pascalwengerter** [comment]
I disagree with the `Expected behaviour` and think the current default (having the OcSelect span 100% of the wrapping element) is a more predictable behaviour than being dependent on longest selectable option (which then could break a lot of styling with various, perhaps dynamically fetched, options).

It should work fine by controling the wrapping element's width, example below can be used on `Personal.vue` for demo purposes

```html
<div class="uk-width-1-3">
  <oc-select
    v-model="selected"
  >
    <template #no-options v-translate>
      No matching role found
    </template>
  </oc-select>
</div>
```

<img width="1207" alt="Screenshot 2021-07-28 at 16 12 42" src="https://user-images.githubusercontent.com/16822008/127337488-60edac18-1fe7-4308-ae66-830c70cbeed2.png">

@elizavetaRa closing this now, please reopen the issue if that's not the case
