### ISSUE TITLE
Future of this repo?

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/owncloud-design-system#2369]
With https://github.com/owncloud/web/pull/7940 merged (which is a big step in terms of developer productivity I think) it's not clear how this repo (and ODS releases) will be handled in the future. Looking forward for a little clarification in e.g. the `README`

**Comment by kulmann** [comment]
We've already created the [stable-14.0](https://github.com/owncloud/owncloud-design-system/tree/stable-14.0) branch in this repo. That will stay here for a while, because the [stable-6.0](https://github.com/owncloud/web/tree/stable-6.0) branch in the ownCloud Web repo relies on that (doesn't have the design system code embedded, like the web master, but uses the npmpjs dependency).

It's probably best to make the `stable-14.0` branch the default branch of this repo and adjust the readme to reflect that main development happens in web now. In a couple of months, when we release the next version of ownCloud Infinite Scale (the next minor or major after `ocis 2.0`) this repo will be archived, as the `stable-14.0` branch in this repo will not be needed anymore.
