### ISSUE TITLE
Button Hover wrong colors

### ISSUE THREAD

**Issue by kulmann** [owncloud/owncloud-design-system#899]
### Steps to reproduce
1. Hover over a primary button

### Expected behaviour
The text should still be visible.

### Actual behaviour
The text turns into a strange color and the text is not visible anymore. See screenshot.

Weird thing is that this doesn't happen in ODS, but only in phoenix.

<img width="141" alt="Screenshot 2020-10-09 at 09 31 45" src="https://user-images.githubusercontent.com/3532843/95555969-da1db080-0a12-11eb-9a58-22ae8acc1fb3.png">

**Comment by pascalwengerter** [comment]
@kulmann and @LukasHirt can't reproduce this one, could you provide more details (or has it been fixed)?

**Comment by LukasHirt** [comment]
@pascalwengerter You can see this e.g. when visiting the account page (you can use web.owncloud.com demo instance). On the right side next to the heading is a button to edit users profile. That is a link with button styling. On hover, the link changes colour to the primary action which is the same as the background.

**Comment by pascalwengerter** [comment]
Ok I spent some time trying to figure things out...

Turns out the `:hover` behaviour of the **oc-button-component** is different for `type="a"` and `type="button"`: Since it is not specified in the `oc-button.scss`, the **ui-kit** defaults get used (that's my understanding, at least). 


I wasn't able to reproduce this since I only checked the ownCloud.design documentation (which defaults to `<button>`).

Opening a PR to fix this in a minute!
